### ISSUE TITLE
[2pt] Login page

### ISSUE THREAD

**Issue by Elerqsousy** [Elerqsousy/grandeur-backend#7]
Create login page using react.
- User should be able to login using username.
- Styling and responsiveness
  - Make the app responsive, creating both mobile and desktop versions.
  - You should follow the layout of[ the provided design](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign). You should change only the titles, descriptions, and photos - in order to create a website about something other than motorcycles.

**Comment by kessie2862** [comment]
[Link to pull request](https://github.com/Elerqsousy/grandeur-frontend/pull/3)
